name: Publish Docker Images to AWS ECR

on:
  push:
    branches:
      - "feat/aws-ecr"

jobs:
  push_public_ecr:
    name: Push docker imahes to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: ap-southeast-3

      - name: Setup qemu
        uses: docker/setup-qemu-action@v2

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Build and push Docker images
        id: build-and-push
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: public.ecr.aws/z7n3e9v0/caddy-mod:latest
