name: Publish Docker Images

on:
 push:
    branches:
      - 'master'

jobs:
  push_to_docker_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker images
        id: build-and-push-latest
        uses: docker/build-push-action@v3.1.1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
          tags: isenganime/caddy-mod:latest
          labels: ${{ steps.meta.outputs.label }}