name: Publish Docker Images to AWS ECR

on:
  push:
    branches:
      - "feat/aws-ecr"

jobs:
  push_public_ecr:
    name: Push docker imahes to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3

      - name: Login to AWS ECR
        id: login-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: public.ecr.aws/z7n3e9v0/caddy-mod
          registry-type: public


      - name: Setup qemu
        uses: docker/setup-qemu-action@v2

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Build and push Docker images
        id: build-and-push
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.login-ecr-public.outputs.registry }}/caddy-mod:latest
